version: 2.1

workflows:
  code-rot-check-daily:
    triggers:
      - schedule:
          cron: "1 18 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build-and-test
  main:
    jobs:
      - build-and-test:
          filters:
            tags:
              only:  /.*/

      - deploy-to-pypi:
          requires:
            - build-and-test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/  


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7
    resource_class: small
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    steps:
      - checkout
      - run:
          name: build
          command: |
            sudo apt-get update -y
            sudo apt-get install cmake -y 
            pip install -e .
      - run:
          name: Try to import
          command: python -c "from rmn import RMN"
      - run:
          name: Inference
          command: |
            curl "https://user-images.githubusercontent.com/24642166/117108145-f7e6a480-adac-11eb-9786-a3e50a3cdea6.jpg" -o "image.png"
            python -c "import cv2; from rmn import RMN; print(RMN().detect_emotion_for_single_frame(cv2.imread('image.png')))"
  
  deploy-to-pypi:
    docker:
      - image: cimg/python:3.7
    resource_class: small
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $pu" >> ~/.pypirc
            echo -e "password = $pp" >> ~/.pypirc
      - run: 
          name: create package
          command: |
            pip install wheel twine
            python setup.py sdist bdist_wheel
      - run: 
          name: upload
          command: twine upload dist/*



